# Generated by Django 5.2 on 2025-04-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[
                    ("first", "Первый курс"),
                    ("second", "Второй курс"),
                    ("third", "Третий курс"),
                    ("fourth", "Четвертый курс"),
                ],
                default="first",
                max_length=6,
                verbose_name="Курс",
            ),
        ),
    ]
